spring:

  datasource:
    url: jdbc:mysql://localhost:3306/viasofttest
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect


  liquibase:
    change-log: classpath:config/liquibase/master.xml
    enabled: true

nfe:
  url: "http://www.nfe.fazenda.gov.br/portal/disponibilidade.aspx"



