name: viasofttest
services:
  mysql:
    image: mysql:8.3.0
    volumes:
      - ./config/mysql:/etc/mysql/conf.d
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=viasofttest
    ports:
      - 127.0.0.1:3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    healthcheck:
      test: ['CMD', 'mysql', '-e', 'SHOW DATABASES;']
      interval: 5s
      timeout: 5s
      retries: 10
